import React from 'react';

interface BookCoverProps {
  month: string;
  size?: 'small' | 'medium' | 'large';
}

export default function BookCover({ month, size = 'medium' }: BookCoverProps) {
  // Scale factors for different sizes
  const scales = {
    small: 0.6,
    medium: 0.8,
    large: 1.0,
  };

  const scale = scales[size];
  const width = 300 * scale;
  const height = 450 * scale;

  // Complete month data extracted from original HTML
  const getMonthData = (monthName: string) => {
    const monthsData: Record<string, any> = {
      January: {
        icon: '❄️',
        background: `
          radial-gradient(circle 3px at 18% 22%, white 50%, rgba(255, 255, 255, 0.8) 60%, transparent 70%),
          radial-gradient(circle 2px at 73% 31%, white 50%, rgba(255, 255, 255, 0.9) 60%, transparent 70%),
          radial-gradient(circle 4px at 42% 68%, white 50%, rgba(255, 255, 255, 0.7) 60%, transparent 70%),
          radial-gradient(circle 2px at 87% 79%, white 50%, rgba(255, 255, 255, 0.8) 60%, transparent 70%),
          radial-gradient(circle 3px at 11% 63%, white 50%, rgba(255, 255, 255, 0.6) 60%, transparent 70%),
          radial-gradient(circle 2px at 94% 38%, white 50%, rgba(255, 255, 255, 0.9) 60%, transparent 70%),
          radial-gradient(circle 3px at 67% 15%, white 50%, rgba(255, 255, 255, 0.7) 60%, transparent 70%),
          radial-gradient(circle 2px at 29% 89%, white 50%, rgba(255, 255, 255, 0.8) 60%, transparent 70%),
          radial-gradient(circle 2px at 56% 43%, white 50%, rgba(255, 255, 255, 0.7) 60%, transparent 70%),
          radial-gradient(circle 1px at 35% 17%, rgba(255, 255, 255, 0.9) 100%, transparent 100%),
          radial-gradient(circle 1px at 81% 54%, rgba(255, 255, 255, 0.8) 100%, transparent 100%),
          radial-gradient(circle 1px at 24% 76%, rgba(255, 255, 255, 0.7) 100%, transparent 100%),
          radial-gradient(circle 1px at 62% 12%, rgba(255, 255, 255, 0.8) 100%, transparent 100%),
          radial-gradient(circle 1px at 8% 34%, rgba(255, 255, 255, 0.6) 100%, transparent 100%),
          radial-gradient(circle 1px at 91% 67%, rgba(255, 255, 255, 0.9) 100%, transparent 100%),
          radial-gradient(circle 1px at 37% 95%, rgba(255, 255, 255, 0.7) 100%, transparent 100%),
          radial-gradient(circle 1px at 74% 26%, rgba(255, 255, 255, 0.5) 100%, transparent 100%),
          radial-gradient(circle 1px at 15% 48%, rgba(255, 255, 255, 0.8) 100%, transparent 100%),
          radial-gradient(circle 1px at 88% 83%, rgba(255, 255, 255, 0.6) 100%, transparent 100%),
          radial-gradient(circle 1px at 46% 7%, rgba(255, 255, 255, 0.9) 100%, transparent 100%),
          linear-gradient(135deg, #0f3460 0%, #2c5282 50%, #4299e1 100%)
        `,
        beforeBg: '',
        beforeBgSize: 'auto',
        animation: 'rotate',
        titleFont: 'font-orbitron',
        titleColor: '#e6f3ff',
        titleSize: 28,
        titleWeight: 'bold',
        sudokuData: [
          '7',
          '',
          '3',
          '',
          '5',
          '',
          '9',
          '',
          '1',
          '',
          '8',
          '',
          '7',
          '',
          '1',
          '',
          '3',
          '',
          '4',
          '',
          '6',
          '',
          '9',
          '',
          '8',
          '',
          '5',
          '',
          '2',
          '',
          '6',
          '',
          '8',
          '',
          '9',
          '',
          '1',
          '',
          '9',
          '',
          '7',
          '',
          '3',
          '',
          '6',
          '',
          '6',
          '',
          '3',
          '',
          '4',
          '',
          '1',
          '',
          '3',
          '',
          '1',
          '',
          '8',
          '',
          '2',
          '',
          '9',
          '',
          '9',
          '',
          '4',
          '',
          '6',
          '',
          '8',
          '',
          '6',
          '',
          '8',
          '',
          '1',
          '',
          '4',
          '',
          '7',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Basic to Beyond Brutal Techniques',
          line3: '❄️ Winter Challenge Edition ❄️',
        },
      },

      February: {
        icon: '💕',
        background:
          'linear-gradient(135deg, #ff6b9d 0%, #e91e63 50%, #ffc1cc 100%)',
        beforeBg: `
          radial-gradient(ellipse at 30% 40%, rgba(255, 182, 193, 0.8) 20px, transparent 25px),
          radial-gradient(ellipse at 70% 60%, rgba(255, 105, 180, 0.6) 15px, transparent 20px),
          radial-gradient(ellipse at 20% 80%, rgba(255, 20, 147, 0.7) 18px, transparent 23px),
          radial-gradient(ellipse at 80% 20%, rgba(255, 182, 193, 0.5) 12px, transparent 17px)
        `,
        beforeBgSize: '150px 150px, 200px 200px, 180px 180px, 120px 120px',
        beforeOpacity: 0.6,
        animation: 'heartBeat',
        titleFont: 'font-pacifico',
        titleColor: '#ffb3d9',
        titleSize: 36,
        titleWeight: 'normal',
        sudokuData: [
          '2',
          '',
          '1',
          '4',
          '',
          '8',
          '5',
          '',
          '3',
          '',
          '4',
          '',
          '',
          '3',
          '',
          '',
          '1',
          '',
          '8',
          '',
          '3',
          '1',
          '',
          '5',
          '4',
          '',
          '9',
          '4',
          '8',
          '',
          '',
          '1',
          '',
          '',
          '3',
          '2',
          '',
          '1',
          '2',
          '8',
          '',
          '4',
          '9',
          '6',
          '',
          '3',
          '6',
          '',
          '',
          '2',
          '',
          '',
          '4',
          '1',
          '1',
          '',
          '4',
          '3',
          '',
          '6',
          '2',
          '',
          '8',
          '',
          '2',
          '',
          '',
          '8',
          '',
          '',
          '5',
          '',
          '5',
          '',
          '8',
          '2',
          '',
          '1',
          '3',
          '',
          '4',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'From Hidden Singles to AIC Chains',
          line3: '💕 Love the Challenge 💕',
        },
      },

      March: {
        icon: '🌸',
        background:
          'linear-gradient(135deg, #11998e 0%, #38ef7d 50%, #ffd89b 100%)',
        beforeBg: `
          conic-gradient(from 0deg at 25% 25%, rgba(255, 182, 193, 0.8) 36deg, transparent 37deg, transparent 71deg, rgba(255, 192, 203, 0.6) 72deg, rgba(255, 182, 193, 0.8) 108deg, transparent 109deg),
          conic-gradient(from 45deg at 75% 35%, rgba(255, 182, 193, 0.7) 36deg, transparent 37deg, transparent 71deg, rgba(255, 192, 203, 0.5) 72deg, rgba(255, 182, 193, 0.7) 108deg, transparent 109deg),
          conic-gradient(from 90deg at 40% 80%, rgba(255, 182, 193, 0.6) 36deg, transparent 37deg, transparent 71deg, rgba(255, 192, 203, 0.4) 72deg, rgba(255, 182, 193, 0.6) 108deg, transparent 109deg)
        `,
        beforeBgSize: '80px 80px, 60px 60px, 100px 100px',
        beforeOpacity: 0.5,
        animation: 'bounce',
        titleFont: 'serif',
        titleFontFamily: '"Times New Roman", serif',
        titleColor: 'white',
        titleSize: 30,
        titleWeight: 'normal',
        fontStyle: 'italic',
        sudokuData: [
          '9',
          '3',
          '',
          '8',
          '',
          '2',
          '',
          '1',
          '7',
          '',
          '8',
          '1',
          '',
          '7',
          '',
          '3',
          '4',
          '',
          '7',
          '',
          '4',
          '3',
          '',
          '1',
          '8',
          '',
          '5',
          '3',
          '',
          '7',
          '4',
          '8',
          '',
          '1',
          '',
          '9',
          '4',
          '1',
          '',
          '',
          '3',
          '',
          '',
          '7',
          '8',
          '8',
          '',
          '5',
          '',
          '1',
          '7',
          '4',
          '',
          '2',
          '1',
          '',
          '8',
          '7',
          '',
          '4',
          '9',
          '',
          '3',
          '',
          '4',
          '3',
          '',
          '2',
          '',
          '7',
          '8',
          '',
          '2',
          '7',
          '',
          '1',
          '',
          '8',
          '',
          '5',
          '4',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Spring into Advanced Techniques',
          line3: '🌸 Fresh Challenges Bloom 🌸',
        },
      },

      April: {
        icon: '🌈',
        background:
          'linear-gradient(135deg, #667eea 0%, #764ba2 20%, #f093fb 40%, #f5576c 60%, #4facfe 80%, #00f2fe 100%)',
        beforeBg: `
          repeating-linear-gradient(45deg, transparent, transparent 8px, rgba(255, 255, 255, 0.1) 8px, rgba(255, 255, 255, 0.1) 15px),
          repeating-linear-gradient(1deg, transparent, transparent 4px, rgba(255, 255, 255, 0.08) 5px, rgba(255, 255, 255, 0.08) 6px, transparent 7px),
          repeating-linear-gradient(-1deg, transparent, transparent 6px, rgba(255, 255, 255, 0.06) 7px, rgba(255, 255, 255, 0.06) 8px, transparent 9px)
        `,
        beforeBgSize: '500px 500px, 100% 25px, 100% 30px',
        animation: 'sway',
        titleFont: 'sans-serif',
        titleFontFamily: 'Arial, sans-serif',
        titleColor: 'white',
        titleSize: 26,
        titleWeight: '900',
        titleTransform: 'uppercase',
        sudokuData: [
          '6',
          '1',
          '',
          '5',
          '9',
          '',
          '',
          '2',
          '8',
          '',
          '5',
          '9',
          '',
          '2',
          '',
          '1',
          '6',
          '',
          '2',
          '',
          '8',
          '6',
          '',
          '1',
          '9',
          '',
          '5',
          '5',
          '6',
          '',
          '9',
          '8',
          '',
          '',
          '1',
          '2',
          '9',
          '',
          '1',
          '',
          '5',
          '',
          '8',
          '',
          '6',
          '8',
          '2',
          '',
          '',
          '1',
          '6',
          '',
          '9',
          '4',
          '1',
          '',
          '5',
          '8',
          '',
          '2',
          '6',
          '',
          '9',
          '',
          '8',
          '2',
          '',
          '6',
          '',
          '5',
          '4',
          '',
          '4',
          '9',
          '',
          '',
          '3',
          '5',
          '',
          '8',
          '1',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Weather Any Solving Storm',
          line3: '🌈 After Rain Comes Victory 🌈',
        },
      },

      May: {
        icon: '🌻',
        background:
          'linear-gradient(135deg, #ffeaa7 0%, #fab1a0 30%, #fd79a8 60%, #fdcb6e 100%)',
        beforeBg: `
          radial-gradient(circle at 30% 20%, rgba(255, 165, 0, 0.8) 10px, rgba(255, 140, 0, 0.6) 15px, transparent 20px),
          radial-gradient(circle at 70% 40%, rgba(255, 165, 0, 0.7) 8px, rgba(255, 140, 0, 0.5) 12px, transparent 16px),
          radial-gradient(circle at 20% 70%, rgba(255, 165, 0, 0.6) 12px, rgba(255, 140, 0, 0.4) 18px, transparent 22px),
          radial-gradient(circle at 80% 80%, rgba(255, 165, 0, 0.7) 9px, rgba(255, 140, 0, 0.5) 14px, transparent 18px)
        `,
        beforeBgSize: '120px 120px, 80px 80px, 150px 150px, 100px 100px',
        animation: 'gentleGlow',
        titleFont: 'font-pacifico',
        titleColor: 'white',
        titleSize: 34,
        titleWeight: 'normal',
        sudokuData: [
          '',
          '7',
          '5',
          '1',
          '4',
          '',
          '8',
          '2',
          '',
          '1',
          '',
          '4',
          '8',
          '',
          '2',
          '5',
          '',
          '7',
          '8',
          '2',
          '',
          '5',
          '7',
          '',
          '',
          '1',
          '4',
          '7',
          '',
          '1',
          '2',
          '5',
          '',
          '9',
          '',
          '8',
          '',
          '8',
          '2',
          '7',
          '',
          '1',
          '4',
          '5',
          '',
          '5',
          '',
          '9',
          '',
          '8',
          '4',
          '1',
          '',
          '2',
          '2',
          '5',
          '',
          '4',
          '1',
          '',
          '',
          '8',
          '9',
          '4',
          '',
          '8',
          '9',
          '',
          '5',
          '2',
          '',
          '1',
          '',
          '1',
          '7',
          '',
          '2',
          '8',
          '6',
          '4',
          '',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Bloom with Brain Power',
          line3: '🌻 May Your Skills Flourish 🌻',
        },
      },

      June: {
        icon: '☀️',
        background:
          'linear-gradient(135deg, #74b9ff 0%, #0984e3 50%, #00cec9 100%)',
        beforeBg: `
          radial-gradient(circle at 50% 30%, rgba(255, 255, 0, 0.8) 15px, rgba(255, 215, 0, 0.6) 25px, transparent 35px),
          repeating-linear-gradient(45deg, transparent, transparent 20px, rgba(255, 255, 255, 0.1) 21px, rgba(255, 255, 255, 0.1) 22px),
          conic-gradient(from 0deg at 50% 30%, rgba(255, 255, 0, 0.3) 0deg, transparent 20deg, rgba(255, 215, 0, 0.2) 40deg, transparent 60deg)
        `,
        beforeBgSize: '200px 200px, 30px 30px, 100px 100px',
        animation: 'pulse',
        titleFont: 'font-orbitron',
        titleColor: 'white',
        titleSize: 28,
        titleWeight: '700',
        sudokuData: [
          '3',
          '',
          '8',
          '7',
          '2',
          '',
          '1',
          '',
          '4',
          '7',
          '2',
          '',
          '',
          '1',
          '',
          '',
          '8',
          '3',
          '',
          '1',
          '4',
          '8',
          '',
          '3',
          '7',
          '2',
          '',
          '8',
          '3',
          '',
          '2',
          '7',
          '',
          '',
          '4',
          '1',
          '2',
          '',
          '1',
          '4',
          '',
          '8',
          '3',
          '',
          '7',
          '4',
          '7',
          '',
          '',
          '3',
          '1',
          '',
          '6',
          '8',
          '',
          '8',
          '2',
          '1',
          '',
          '7',
          '4',
          '3',
          '',
          '1',
          '4',
          '',
          '',
          '8',
          '',
          '',
          '7',
          '2',
          '6',
          '',
          '7',
          '',
          '4',
          '2',
          '8',
          '',
          '5',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Summer Brain Training',
          line3: '☀️ Sunny Side of Solving ☀️',
        },
      },

      July: {
        icon: '🏖️',
        background:
          'linear-gradient(135deg, #fd79a8 0%, #fdcb6e 30%, #e17055 60%, #00b894 100%)',
        beforeBg: `
          repeating-linear-gradient(90deg, rgba(255, 255, 255, 0.1) 0px, rgba(255, 255, 255, 0.1) 2px, transparent 2px, transparent 30px),
          repeating-linear-gradient(0deg, transparent, transparent 8px, rgba(255, 255, 255, 0.2) 10px, rgba(255, 255, 255, 0.2) 12px),
          linear-gradient(45deg, rgba(255, 215, 0, 0.2) 25%, transparent 25%, transparent 75%, rgba(255, 215, 0, 0.2) 75%)
        `,
        beforeBgSize: '100% 30px, 200px 200px, 25px 25px',
        animation: 'wave',
        titleFont: 'sans-serif',
        titleFontFamily: 'Impact, "Arial Black", sans-serif',
        titleColor: 'white',
        titleSize: 32,
        titleWeight: 'normal',
        sudokuData: [
          '5',
          '8',
          '',
          '3',
          '6',
          '',
          '',
          '1',
          '2',
          '',
          '3',
          '2',
          '1',
          '',
          '8',
          '5',
          '4',
          '',
          '1',
          '',
          '4',
          '2',
          '',
          '5',
          '6',
          '',
          '3',
          '2',
          '1',
          '',
          '6',
          '3',
          '',
          '',
          '8',
          '4',
          '3',
          '',
          '8',
          '5',
          '',
          '2',
          '1',
          '',
          '6',
          '4',
          '6',
          '',
          '',
          '8',
          '1',
          '',
          '2',
          '9',
          '',
          '4',
          '3',
          '8',
          '',
          '6',
          '2',
          '5',
          '',
          '8',
          '2',
          '',
          '',
          '1',
          '',
          '',
          '6',
          '7',
          '6',
          '',
          '1',
          '',
          '2',
          '3',
          '4',
          '',
          '8',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Beach Reading, Brain Training',
          line3: '🏖️ Vacation Mind Games 🏖️',
        },
      },

      August: {
        icon: '🔥',
        background:
          'linear-gradient(135deg, #ff4757 0%, #ff6348 20%, #ff7675 40%, #fd79a8 60%, #fdcb6e 80%, #e17055 100%)',
        beforeBg: `
          conic-gradient(from 0deg at 75% 25%, rgba(255, 255, 0, 0.6) 0deg, transparent 15deg, rgba(255, 215, 0, 0.5) 30deg, transparent 45deg, rgba(255, 255, 0, 0.6) 60deg, transparent 75deg, rgba(255, 215, 0, 0.4) 90deg, transparent 105deg, rgba(255, 255, 0, 0.6) 120deg, transparent 135deg, rgba(255, 215, 0, 0.5) 150deg, transparent 165deg, rgba(255, 255, 0, 0.6) 180deg, transparent 195deg, rgba(255, 215, 0, 0.4) 210deg, transparent 225deg, rgba(255, 255, 0, 0.6) 240deg, transparent 255deg, rgba(255, 215, 0, 0.5) 270deg, transparent 285deg, rgba(255, 255, 0, 0.6) 300deg, transparent 315deg, rgba(255, 215, 0, 0.4) 330deg, transparent 345deg),
          radial-gradient(circle at 75% 25%, rgba(255, 255, 255, 0.9) 15px, rgba(255, 255, 0, 0.8) 25px, rgba(255, 215, 0, 0.6) 40px, rgba(255, 140, 0, 0.4) 60px, transparent 80px),
          repeating-linear-gradient(1deg, transparent, transparent 4px, rgba(255, 255, 255, 0.08) 5px, rgba(255, 255, 255, 0.08) 6px, transparent 7px),
          repeating-linear-gradient(-1deg, transparent, transparent 6px, rgba(255, 255, 255, 0.06) 7px, rgba(255, 255, 255, 0.06) 8px, transparent 9px),
          repeating-linear-gradient(2deg, transparent, transparent 8px, rgba(255, 255, 255, 0.04) 9px, rgba(255, 255, 255, 0.04) 10px, transparent 11px)
        `,
        beforeBgSize:
          '400px 400px, 200px 200px, 100% 25px, 100% 30px, 100% 35px',
        animation: 'blaze',
        titleFont: 'font-orbitron',
        titleColor: 'white',
        titleSize: 30,
        titleWeight: 900,
        sudokuData: [
          '',
          '6',
          '3',
          '4',
          '1',
          '',
          '9',
          '7',
          '',
          '4',
          '',
          '1',
          '9',
          '',
          '7',
          '3',
          '',
          '6',
          '9',
          '7',
          '',
          '3',
          '6',
          '',
          '',
          '1',
          '4',
          '1',
          '',
          '7',
          '6',
          '9',
          '',
          '4',
          '',
          '2',
          '6',
          '4',
          '',
          '1',
          '',
          '2',
          '',
          '8',
          '7',
          '2',
          '',
          '8',
          '',
          '7',
          '4',
          '1',
          '',
          '9',
          '7',
          '2',
          '',
          '',
          '4',
          '1',
          '',
          '9',
          '3',
          '3',
          '',
          '4',
          '2',
          '',
          '9',
          '6',
          '',
          '1',
          '',
          '1',
          '9',
          '',
          '3',
          '6',
          '2',
          '4',
          '',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Heat Up Your Brain Power',
          line3: '🔥 Scorching Hot Challenges 🔥',
        },
      },

      September: {
        icon: '📚',
        background:
          'linear-gradient(135deg, #a29bfe 0%, #6c5ce7 30%, #fd79a8 60%, #fdcb6e 100%)',
        beforeBg: `
          repeating-linear-gradient(0deg, rgba(139, 69, 19, 0.3) 0px, rgba(139, 69, 19, 0.3) 2px, transparent 3px, transparent 8px),
          repeating-linear-gradient(0deg, rgba(160, 82, 45, 0.2) 0px, rgba(160, 82, 45, 0.2) 1px, transparent 2px, transparent 15px),
          linear-gradient(45deg, rgba(255, 215, 0, 0.2) 25%, transparent 25%, transparent 75%, rgba(255, 215, 0, 0.2) 75%),
          linear-gradient(-45deg, rgba(255, 215, 0, 0.2) 25%, transparent 25%, transparent 75%, rgba(255, 215, 0, 0.2) 75%)
        `,
        beforeBgSize: '100% 20px, 100% 30px, 20px 20px, 20px 20px',
        animation: 'wiggle',
        titleFont: 'serif',
        titleFontFamily: 'Georgia, "Times New Roman", serif',
        titleColor: 'white',
        titleSize: 28,
        titleWeight: 'normal',
        sudokuData: [
          '8',
          '',
          '2',
          '7',
          '5',
          '',
          '4',
          '',
          '1',
          '',
          '5',
          '7',
          '',
          '1',
          '',
          '8',
          '2',
          '',
          '1',
          '4',
          '',
          '2',
          '',
          '8',
          '',
          '5',
          '7',
          '7',
          '8',
          '',
          '',
          '3',
          '',
          '',
          '9',
          '',
          '2',
          '4',
          '',
          '',
          '6',
          '',
          '',
          '1',
          '5',
          '',
          '9',
          '',
          '4',
          '8',
          '',
          '3',
          '',
          '6',
          '3',
          '',
          '1',
          '',
          '7',
          '2',
          '9',
          '',
          '4',
          '',
          '',
          '',
          '',
          '5',
          '',
          '',
          '6',
          '',
          '',
          '8',
          '',
          '',
          '3',
          '',
          '1',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'School Your Brain',
          line3: '📚 Knowledge Through Numbers 📚',
        },
      },

      October: {
        icon: '🎃',
        background:
          'linear-gradient(135deg, #2d1b69 0%, #8b008b 50%, #ff6347 100%)',
        beforeBg: `
          radial-gradient(ellipse at 25% 75%, rgba(255, 140, 0, 0.4) 60px, rgba(255, 69, 0, 0.2) 120px, transparent 180px),
          radial-gradient(ellipse at 80% 25%, rgba(220, 220, 220, 0.3) 50px, rgba(200, 200, 200, 0.1) 100px, transparent 150px),
          radial-gradient(circle at 30% 30%, rgba(139, 0, 139, 0.4) 40px, transparent 70px)
        `,
        beforeBgSize: '400px 400px, 300px 300px, 200px 200px',
        animation: 'spooky',
        titleFont: 'font-creepster',
        titleColor: '#ff6b35',
        titleSize: 24,
        titleWeight: 'normal',
        sudokuData: [
          '3',
          '9',
          '',
          '6',
          '',
          '1',
          '',
          '2',
          '4',
          '',
          '1',
          '6',
          '4',
          '2',
          '',
          '3',
          '9',
          '',
          '4',
          '2',
          '',
          '9',
          '3',
          '',
          '',
          '1',
          '6',
          '9',
          '',
          '4',
          '',
          '1',
          '',
          '',
          '5',
          '',
          '7',
          '',
          '8',
          '',
          '',
          '6',
          '',
          '',
          '2',
          '1',
          '',
          '5',
          '',
          '9',
          '4',
          '',
          '3',
          '',
          '2',
          '7',
          '',
          '6',
          '',
          '8',
          '1',
          '',
          '',
          '',
          '',
          '4',
          '',
          '',
          '7',
          '',
          '',
          '8',
          '',
          '',
          '9',
          '',
          '3',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Spooky Smart Challenges',
          line3: '🎃 Frighteningly Fun 🎃',
        },
      },

      November: {
        icon: '🍂',
        background:
          'linear-gradient(135deg, #1a1a2e 0%, #2d1b69 30%, #ff6b35 70%, #f7931e 100%)',
        beforeBg: `
          radial-gradient(ellipse at 50% 120%, rgba(255, 140, 0, 0.6) 100px, rgba(255, 69, 0, 0.4) 200px, rgba(255, 215, 0, 0.2) 300px, transparent 400px),
          radial-gradient(circle at 75% 25%, rgba(255, 255, 255, 0.9) 3px, rgba(255, 215, 0, 0.7) 5px, transparent 6px),
          radial-gradient(circle at 25% 40%, rgba(210, 105, 30, 0.7) 3px, transparent 4px),
          radial-gradient(circle at 20% 70%, rgba(255, 140, 0, 0.5) 3px, transparent 4px)
        `,
        beforeBgSize: '800px 600px, 100% 100%, 100% 100%, 100% 100%',
        animation: 'fall',
        titleFont: 'serif',
        titleFontFamily: 'Georgia, "Times New Roman", serif',
        titleColor: 'white',
        titleSize: 30,
        titleWeight: 'normal',
        fontStyle: 'italic',
        sudokuData: [
          '',
          '4',
          '1',
          '5',
          '8',
          '',
          '2',
          '3',
          '',
          '5',
          '',
          '3',
          '2',
          '',
          '4',
          '1',
          '',
          '8',
          '2',
          '8',
          '',
          '1',
          '3',
          '',
          '',
          '4',
          '5',
          '8',
          '2',
          '',
          '',
          '7',
          '',
          '',
          '1',
          '',
          '6',
          '',
          '9',
          '',
          '',
          '4',
          '',
          '',
          '7',
          '3',
          '',
          '8',
          '',
          '1',
          '2',
          '',
          '5',
          '',
          '4',
          '6',
          '',
          '',
          '9',
          '7',
          '',
          '',
          '',
          '',
          '3',
          '',
          '',
          '6',
          '',
          '',
          '9',
          '',
          '',
          '8',
          '',
          '4',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Bonfire Night Brain Burners',
          line3: '🍂 Remember, Remember! 🍂',
        },
      },

      December: {
        icon: '🎄',
        background:
          'linear-gradient(135deg, #0f1c3f 0%, #1a5724 30%, #c41e3a 60%, #2c5234 80%, #ffffff 100%)',
        beforeBg: `
          radial-gradient(circle at 50% 20%, rgba(255, 215, 0, 0.95) 4px, rgba(255, 215, 0, 0.7) 8px, rgba(255, 255, 255, 0.3) 12px, transparent 16px),
          radial-gradient(circle at 15% 25%, rgba(255, 0, 0, 0.8) 2px, transparent 4px),
          radial-gradient(circle at 25% 30%, rgba(0, 255, 0, 0.8) 2px, transparent 4px),
          radial-gradient(circle at 35% 27%, rgba(255, 215, 0, 0.8) 2px, transparent 4px),
          radial-gradient(circle at 45% 32%, rgba(0, 0, 255, 0.8) 2px, transparent 4px),
          radial-gradient(circle at 55% 28%, rgba(255, 0, 0, 0.8) 2px, transparent 4px),
          radial-gradient(circle at 65% 33%, rgba(0, 255, 0, 0.8) 2px, transparent 4px),
          radial-gradient(circle at 75% 29%, rgba(255, 215, 0, 0.8) 2px, transparent 4px),
          radial-gradient(circle at 85% 34%, rgba(0, 0, 255, 0.8) 2px, transparent 4px)
        `,
        beforeBgSize:
          '300px 300px, 100% 100%, 100% 100%, 100% 100%, 100% 100%, 100% 100%, 100% 100%, 100% 100%, 100% 100%',
        animation: 'twinkle',
        titleFont: 'font-orbitron',
        titleColor: '#fff',
        titleSize: 28,
        titleWeight: '700',
        sudokuData: [
          '7',
          '3',
          '',
          '8',
          '1',
          '',
          '',
          '6',
          '2',
          '',
          '8',
          '2',
          '6',
          '',
          '7',
          '1',
          '3',
          '',
          '6',
          '1',
          '',
          '2',
          '3',
          '',
          '',
          '8',
          '7',
          '2',
          '',
          '8',
          '',
          '4',
          '',
          '',
          '9',
          '',
          '5',
          '',
          '7',
          '',
          '',
          '1',
          '',
          '',
          '4',
          '9',
          '',
          '6',
          '',
          '2',
          '1',
          '',
          '8',
          '3',
          '',
          '5',
          '',
          '9',
          '4',
          '',
          '',
          '',
          '',
          '3',
          '',
          '',
          '7',
          '',
          '',
          '2',
          '',
          '',
          '6',
          '',
          '5',
        ],
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Holiday Brain Gifts',
          line3: "🎄 Season's Greetings Solver! 🎄",
        },
      },
    };

    return (
      monthsData[monthName] || {
        icon: '📅',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        beforeBg: '',
        animation: '',
        titleFont: 'Arial',
        titleColor: 'white',
        titleSize: 32,
        titleWeight: 'bold',
        sudokuData: Array(81).fill(''),
        stats: {
          line1: '50 Puzzles • Multiple Difficulties',
          line2: 'Challenge Your Mind',
          line3: '🧩 Puzzle Power 🧩',
        },
      }
    );
  };

  const monthData = getMonthData(month);

  const getAnimationClass = (animation: string) => {
    const animationMap: Record<string, string> = {
      rotate: 'animate-rotate',
      heartBeat: 'animate-heartBeat',
      bounce: 'animate-bounce',
      sway: 'animate-sway',
      gentleGlow: 'animate-gentleGlow',
      pulse: 'animate-pulse',
      wave: 'animate-wave',
      blaze: 'animate-blaze',
      wiggle: 'animate-wiggle',
      spooky: 'animate-spooky',
      fall: 'animate-fall',
      twinkle: 'animate-twinkle',
    };
    return animationMap[animation] || '';
  };

  return (
    <div className="relative inline-block">
      {/* Cover container */}
      <div
        className="relative overflow-hidden"
        style={{
          width: `${width}px`,
          height: `${height}px`,
          borderRadius: `${15 * scale}px`,
          boxShadow: `0 ${20 * scale}px ${40 * scale}px rgba(0, 0, 0, 0.3)`,
          margin: '0 auto',
        }}
      >
        {/* Background */}
        <div
          className="absolute inset-0"
          style={{ background: monthData.background }}
        />

        {/* Before overlay (::before equivalent) */}
        {monthData.beforeBg && (
          <div
            className={`absolute inset-0 ${monthData.animation === 'heatShimmer' ? 'animate-heatShimmer' : ''}`}
            style={{
              background: monthData.beforeBg,
              backgroundSize: monthData.beforeBgSize,
              opacity: monthData.beforeOpacity || 1,
              animationDuration: '3s',
              animationTimingFunction: 'ease-in-out',
              animationIterationCount: 'infinite',
              animationDirection: 'alternate',
            }}
          />
        )}

        {/* Month icon */}
        <div
          className={`absolute ${getAnimationClass(monthData.animation)}`}
          style={{
            right: `${15 * scale}px`,
            top: `${15 * scale}px`,
            fontSize: `${50 * scale}px`,
            width: `${60 * scale}px`,
            height: `${60 * scale}px`,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            opacity: 0.8,
          }}
        >
          {monthData.icon}
        </div>

        {/* Content */}
        <div
          className="relative flex h-full flex-col text-center text-white"
          style={{
            padding: `${30 * scale}px ${25 * scale}px`,
            boxSizing: 'border-box',
          }}
        >
          {/* Title */}
          <h1
            className={monthData.titleFont}
            style={{
              fontSize: `${(monthData.titleSize || 32) * scale}px`,
              fontWeight: monthData.titleWeight || 'bold',
              textShadow: '2px 2px 4px rgba(0, 0, 0, 0.7)',
              marginBottom: `${5 * scale}px`,
              letterSpacing: '1px',
              color: monthData.titleColor,
              fontStyle: monthData.fontStyle || 'normal',
              textTransform: monthData.titleTransform || 'none',
              fontFamily: monthData.titleFontFamily,
            }}
          >
            SUDOKU RACE
          </h1>

          {/* Subtitle */}
          <div
            style={{
              fontSize: `${18 * scale}px`,
              marginBottom: `${20 * scale}px`,
              opacity: 0.9,
              textShadow: '1px 1px 2px rgba(0, 0, 0, 0.7)',
            }}
          >
            {month} Edition
          </div>

          {/* Sudoku Grid */}
          <div
            className="mx-auto my-auto"
            style={{
              width: `${120 * scale}px`,
              height: `${120 * scale}px`,
              margin: `${20 * scale}px auto`,
              border: `${3 * scale}px solid rgba(255, 255, 255, 0.8)`,
              borderRadius: `${8 * scale}px`,
              display: 'grid',
              gridTemplateColumns: 'repeat(9, 1fr)',
              gridTemplateRows: 'repeat(9, 1fr)',
              background: 'rgba(255, 255, 255, 0.9)',
              gap: `${1 * scale}px`,
            }}
          >
            {monthData.sudokuData.map((value: string, index: number) => {
              const row = Math.floor(index / 9);
              const col = index % 9;
              const isThickRight = col === 2 || col === 5;
              const isThickBottom = row === 2 || row === 5;

              return (
                <div
                  key={index}
                  className="flex items-center justify-center"
                  style={{
                    background: 'rgba(255, 255, 255, 0.7)',
                    fontSize: `${8 * scale}px`,
                    color: '#333',
                    fontWeight: 'bold',
                    borderRight: isThickRight
                      ? `${1 * scale}px solid #333`
                      : 'none',
                    borderBottom: isThickBottom
                      ? `${1 * scale}px solid #333`
                      : 'none',
                  }}
                >
                  {value}
                </div>
              );
            })}
          </div>

          {/* Stats */}
          <div
            className="mt-auto"
            style={{
              background: 'rgba(0, 0, 0, 0.3)',
              padding: `${15 * scale}px`,
              borderRadius: `${10 * scale}px`,
              backdropFilter: 'blur(10px)',
              WebkitBackdropFilter: 'blur(10px)',
            }}
          >
            <div
              style={{
                margin: `${3 * scale}px 0`,
                fontSize: `${12 * scale}px`,
              }}
            >
              <strong>{monthData.stats.line1}</strong>
            </div>
            <div
              style={{
                margin: `${3 * scale}px 0`,
                fontSize: `${12 * scale}px`,
              }}
            >
              {monthData.stats.line2}
            </div>
            <div
              style={{
                margin: `${3 * scale}px 0`,
                fontSize: `${12 * scale}px`,
              }}
            >
              {monthData.stats.line3}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
